gocd-server:
    image: c12e/gocd-server
    environment:
      - CONSUL_ADDR=consul.service.consul:8500
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
    ports:
      - 8152:8152
      - 8153:8153
      - 8154:8154
    volumes:
      - shared_certs:/cscerts
gocd-agent:
   image: c12e/gocd-agent
   environment:
     - CONSUL_ADDR=consul.service.consul:8500
     - VAULT_ADDR=${VAULT_ADDR}
     - VAULT_TOKEN=${VAULT_TOKEN}
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /bin/dock.static:/bin/docker
     - shared_certs:/cscerts
   links:
      - gocd-server:go-server
